import { createTheme } from "@mantine/core";
import { themeToVars } from "@mantine/vanilla-extract";

export const theme = createTheme({
    fontFamily: "inherit",
    primaryColor: "primary",

    scale: 1,
    fontSmoothing: true,
    focusRing: "auto",
    white: "#FAFAFA",
    black: "#4C4C4C",

    colors: {
        // https://mantine.dev/colors-generator/?color=395EE5
        primary: [
            "#e8f0ff",
            "#d1dcff",
            "#a3b6fa",
            "#708df3",
            "#3F65EE",
            // "#2b55ec",
            // "#1a4aec",
            // "#093cd2",
            // "#0034bd",
            // "#002da7",
            "#3F65EE",
            "#3F65EE",
            "#3F65EE",
            "#3F65EE",
            "#3F65EE",
        ],
        background: [
            "#EFF0F4",
            "#D3D4D8",
            "#A6A8AE",
            "#75787F",
            "#4D515A",
            "#33393F",
            "#242A30",
            "#14181C",
            "#0A0C0E",
            "#000000",
        ],
        dark: [
            "#fafafa",
            "#e7e7e7",
            "#cdcdcd",
            "#b2b2b2",
            "#9a9a9a",
            "#8b8b8b",
            "#848484",
            "#717171",
            "#656565",
            "#575757",
        ],
        // https://mantine.dev/colors-generator/?color=EDEEF2
        gray: [
            "#fafafa",
            "#e5e5e6",
            "#c7c8cd",
            "#a8aab5",
            "#8d91a1",
            "#7c8094",
            "#737890",
            "#61667d",
            "#565b70",
            "#494e65",
        ],
        info: [
            "#e3fafc",
            "#c5f6fa",
            "#99e9f2",
            "#66d9e8",
            "#3bc9db",
            "#22b8cf",
            "#15aabf",
            "#1098ad",
            "#0c8599",
            "#0b7285",
        ],
        success: [
            "#f4fce3",
            "#e9fac8",
            "#d8f5a2",
            "#c0eb75",
            "#a9e34b",
            "#94d82d",
            "#82c91e",
            "#74b816",
            "#66a80f",
            "#5c940d",
        ],
        warn: [
            "#fff9db",
            "#fff3bf",
            "#ffec99",
            "#ffe066",
            "#ffd43b",
            "#fcc419",
            "#fab005",
            "#f59f00",
            "#f08c00",
            "#e67700",
        ],
        // https://mantine.dev/colors-generator/?color=EA5D5D
        error: [
            "#ffe9e9",
            "#ffd3d3",
            "#f6a6a6",
            "#ee7576",
            "#e84d4d",
            "#e43232",
            "#e42324",
            "#ca1518",
            "#b50d14",
            "#9f000e",
        ],
    },
    primaryShade: {
        light: 6,
        dark: 8,
    },
    autoContrast: false,
    luminanceThreshold: 0.3,
    respectReducedMotion: false,
    cursorType: "default",
    defaultGradient: {
        from: "blue",
        to: "cyan",
        deg: 45,
    },
    defaultRadius: "sm",
    activeClassName: "mantine-active",
    focusClassName: "",
    headings: {
        fontWeight: "700",
        sizes: {
            h1: {
                fontSize: "calc(2.125rem * var(--mantine-scale))",
                lineHeight: "1.3",
            },
            h2: {
                fontSize: "calc(1.625rem * var(--mantine-scale))",
                lineHeight: "1.35",
            },
            h3: {
                fontSize: "calc(1.375rem * var(--mantine-scale))",
                lineHeight: "1.4",
            },
            h4: {
                fontSize: "calc(1.125rem * var(--mantine-scale))",
                lineHeight: "1.45",
            },
            h5: {
                fontSize: "calc(1rem * var(--mantine-scale))",
                lineHeight: "1.5",
            },
            h6: {
                fontSize: "calc(0.875rem * var(--mantine-scale))",
                lineHeight: "1.5",
            },
        },
    },
    fontSizes: {
        xs: "calc(0.75rem * var(--mantine-scale))",
        sm: "calc(0.875rem * var(--mantine-scale))",
        md: "calc(1rem * var(--mantine-scale))",
        lg: "calc(1.125rem * var(--mantine-scale))",
        xl: "calc(1.25rem * var(--mantine-scale))",
    },
    lineHeights: {
        xs: "1.4",
        sm: "1.45",
        md: "1.55",
        lg: "1.6",
        xl: "1.65",
    },
    radius: {
        xs: "calc(0.125rem * var(--mantine-scale))",
        sm: "calc(0.25rem * var(--mantine-scale))",
        md: "calc(0.5rem * var(--mantine-scale))",
        lg: "calc(1rem * var(--mantine-scale))",
        xl: "calc(2rem * var(--mantine-scale))",
    },
    spacing: {
        xs: "calc(0.625rem * var(--mantine-scale))",
        sm: "calc(0.75rem * var(--mantine-scale))",
        md: "calc(1rem * var(--mantine-scale))",
        lg: "calc(1.25rem * var(--mantine-scale))",
        xl: "calc(2rem * var(--mantine-scale))",
    },
    breakpoints: {
        xs: "36em",
        sm: "48em",
        md: "62em",
        lg: "75em",
        xl: "88em",
    },
    shadows: {
        xs: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), 0 calc(0.0625rem * var(--mantine-scale)) calc(0.125rem * var(--mantine-scale)) rgba(0, 0, 0, 0.1)",
        sm: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(0.625rem * var(--mantine-scale)) calc(0.9375rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.4375rem * var(--mantine-scale)) calc(0.4375rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale))",
        md: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(1.25rem * var(--mantine-scale)) calc(1.5625rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.625rem * var(--mantine-scale)) calc(0.625rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale))",
        lg: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(1.75rem * var(--mantine-scale)) calc(1.4375rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.75rem * var(--mantine-scale)) calc(0.75rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale))",
        xl: "0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(2.25rem * var(--mantine-scale)) calc(1.75rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(1.0625rem * var(--mantine-scale)) calc(1.0625rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale))",
    },
    other: {},
    components: {},
});

// https://mantine.dev/styles/vanilla-extract/
// CSS variables object, can be access in *.css.ts files
export const vars = themeToVars(theme);
